### ISSUE TITLE
csdn api changed.

### ISSUE THREAD

**Issue by Haoxiqiang** [ZZy979/csdn-blog-export#1]
*  `get_article_list`: add referer and origin check. It's easily fixed.
```python
REFERER = 'https://javainstalling.blog.csdn.net/?type=blog'
ORIGIN = 'https://javainstalling.blog.csdn.net'

def get_article_list(username):
    url = 'https://blog.csdn.net/community/home-api/v1/get-business-list'
    params = {'page': 1, 'size': 50, 'businessType': 'blog', 'noMore': 'false', 'username': username}
    headers = {'User-Agent': USER_AGENT, 'Referer': REFERER, 'Origin': ORIGIN}
...
```
*  `get_article`: I found csdn add the API crypto check.
1. blog-console-api.csdn.net is deprecated.
2. I've tried to send to `bizapi.csdn.net/blog-console-api/v1/editor/getArticle`, but received `X-Ca-Key is not exist`, `HMAC signature does not match` and other's error messages.
this repo is easy but it may not work for now.

**Comment by ZZy979** [comment]
感谢指出问题！代码中使用的获取文章内容的API确实不可用了。新的API需要添加X-Ca-Key、X-Ca-Signature等几个请求头，网上也有研究生成算法的博客。但我已经不再使用CSDN，所以没有深入研究了。
